### ISSUE TITLE
ANT+ specs

### ISSUE THREAD

**Issue by jesserobertson** [tmcw/running-for-nerds#4]
There's probably a bunch of stuff regarding ANT+ (the protocol used by Suunto/Garmin and others to sync to a computer) etc that you'd want to include. I've had real trouble trying to find a nice way to get my Suunto watch to play nicely on Linux.

**Comment by bhousel** [comment]
I used this once to poke around data on my Garmin 405, but didn't work so well..
https://github.com/mvillalba/python-ant

Now there's openant, which looks pretty sweet:
https://github.com/Tigge/openant
https://github.com/Tigge/antfs-cli
https://github.com/braiden/python-ant-downloader

**Comment by jesserobertson** [comment]
Yeah, wan't too impressed with python-ant. I hadn't seen openant though. Thanks for the link!

**Comment by tmcw** [comment]
Thanks for the notes! Expanded the ANT+ mention into a section that includes these links: https://github.com/tmcw/running-for-nerds/blob/master/README.md#ant
